apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: testgo0401a 
  janus-idp.io/tekton: testgo0401a
  backstage.io/kubernetes-id: testgo0401a
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: testgo0401a
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml