apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: testgo0401a
  janus-idp.io/tekton: testgo0401a
  backstage.io/kubernetes-id: testgo0401a
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: testgo0401a
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
